[app]
name = "attendance-bot"
primary_region = "ord"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256 